<?php
/**
 * You must manually enable this in the menu list, for some reason
 * (even though the test itself enables the module).
 */

require_once drupal_get_path('module', 'simpletest') . '/drupal_web_test_case.php';

class MockStripe {
    public static $charges = array();

    public function add_charge($charge) {
        self::$charges[] = $charge;

        variable_set('mock_stripe_charges', self::$charges);
    }

    public function get_charges() {
        self::$charges = variable_get('mock_stripe_charges');

        return self::$charges;
    }
}

function mock_stripe_menu() {
    debug('mock_stripe', 'menu hook');

    $routes = array();

    $routes['mock_stripe/v1/charges'] = array(
        'page callback' => 'mock_stripe_new_charge',
        'access callback' => TRUE,
        'delivery callback' => 'drupal_json_output',
        'type' => MENU_CALLBACK
    );

    $routes['mock_stripe/mock/charges_made'] = array(
        'page callback' => 'mock_stripe_charges_made',
        'access callback' => TRUE,
        'delivery callback' => 'drupal_json_output',
        'type' => MENU_CALLBACK
    );

    return $routes;
}

function mock_stripe_new_charge() {
    debug('mock_stripe_new_charge');

    $amount = $_POST['amount'];
    $currency = $_POST['currency'];
    $card = $_POST['card'];

    $charge = array(
        'amount' => $amount,
        'currency' => $currency,
        'card' => $card
    );

    MockStripe::add_charge($charge);

    $result = array(
        "id" => "ch_1lT890FuPdj9xX",
        "object" => "charge",
        "created" => 1367637544,
        "livemode" => false,
        "paid" => true,
        "amount" => 12500,
        "currency" => "usd",
        "refunded" => false,
        "fee" => 393,
        "fee_details" => array(
            array(
                "amount" => 393,
                "currency" => $currency,
                "type" => "stripe_fee",
                "description" => "Stripe processing fees",
                "application" => null,
                "amount_refunded_refunded" => 0
            )
        ),
        "card" => array(
            "object" => "card",
            "last4" => "4242",
            "type" => "Visa",
            "exp_month" => 5,
            "exp_year" => 2013,
            "fingerprint" => "rYy7SbfzoN030SaO",
            "country" => "US",
            "name" => "A User",
            "address_line1" => null,
            "address_line2" => null,
            "address_city" => null,
            "address_state" => null,
            "address_zip" => null,
            "address_country" => null,
            "cvc_check" => "pass",
            "address_line1_check" => null,
            "address_zip_check" => null
        ),
        "captured" => true,
        "failure_message" => null,
        "amount_refunded" => 0,
        "customer" => null,
        "invoice" => null,
        "description" => "Order Number: 3",
        "dispute" => null
    );

    return $result;
}

function mock_stripe_charges_made() {
    $result = MockStripe::get_charges();

    return $result;
}